language: php
php:
  - '7.1'
before_script:
  - composer self-update
  - composer install --no-interaction --dev
notifications:
    on_success: never
    on_failure: always
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE myapp_test; GRANT ALL PRIVILEGES ON *.* TO \'stock\'@\'%\' IDENTIFIED BY \'stock\' WITH GRANT OPTION; FLUSH PRIVILEGES;'
