language: php
php:
  - '7.1'
notifications:
    on_success: never
    on_failure: always
services:
  - mysql
before_script:
- mysql -u root -e "CREATE DATABASE stocktest;"
- mysql -u root -e "CREATE USER 'stocktest'@'localhost' IDENTIFIED BY 'stocktest';"
- mysql -u root -e "GRANT ALL ON stocktest.* TO 'stocktest'@'localhost';"
script:
  - ./vendor/bin/phpunit
  - php composer.phar self-update
  - php composer.phar install --no-interaction
  - ./vendor/bin/phpunit
